"""Create players table

Revision ID: 496baed60171
Revises:
Create Date: 2019-08-18 10:01:02.368370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '496baed60171'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('nickname', sa.Text(), nullable=True),
                    sa.Column('vpip', sa.JSON(), nullable=True),
                    sa.Column('pfr', sa.JSON(), nullable=True),
                    sa.Column('threeBet', sa.JSON(), nullable=True),
                    sa.Column('foldToCbet', sa.JSON(), nullable=True),
                    sa.PrimaryKeyConstraint('id'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('players')
    # ### end Alembic commands ###
