"""empty message

Revision ID: b218a7641d00
Revises: 496baed60171
Create Date: 2020-01-04 10:55:43.231419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b218a7641d00'
down_revision = '496baed60171'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('afp', sa.JSON(), nullable=True))
    op.add_column('players', sa.Column('cBet', sa.JSON(), nullable=True))
    op.add_column('players', sa.Column('foldToThreeBet', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'foldToThreeBet')
    op.drop_column('players', 'cBet')
    op.drop_column('players', 'afp')
    # ### end Alembic commands ###
